/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projecte;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import modeldades.Treballador;

/**
 *
 * @author Palanka
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        initMyComponents();
    }
    
    private void initMyComponents() {
        llegirFitxerConfig();
        llegirFitxerDades();
        refresca();
    }
    
    private void llegirFitxerDades(){
        
       if (Projecte.fitxerDades.exists()){
           
           ObjectInputStream entrada=null;
           int i=0;
           try {
               entrada=new ObjectInputStream(new BufferedInputStream(new FileInputStream(Projecte.fitxerDades)));
           
               for(i=0; i<p1.length; i++){
                   p1[i]=(Treballador)entrada.readObject();
                  
               }
               if(i==p1.length){
                   entrada.readObject();
                   JOptionPane.showMessageDialog(this, "Atencio, no tens mes espai a la memoria del fitxer, pots ampliar-la modifican el fitxer config.txt");
                   System.exit(0);
               }
             
               
           } catch (FileNotFoundException ex) {
               JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
           } catch (IOException ex) {
                   //si entrem aqui es que ha anat tot be
                   
                plenes=i;
               if(plenes==p1.length)botoInsertar.setEnabled(false);
           } catch (ClassNotFoundException ex) {
               JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
           }finally{
               
               if(entrada!=null)
                   try{
                       entrada.close();
                   }catch (IOException ex){
                       JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
                   }
           
           }
           
       }
       
    }

    private void llegirFitxerConfig() {
        
        BufferedReader configIn=null;
        PrintWriter configOut=null;
        
        try{
            if(Projecte.fitxerConfig.exists()){
               
                configIn=new BufferedReader(new FileReader(Projecte.fitxerConfig));
                p1=new Treballador[Integer.parseInt(configIn.readLine().strip())];

            }else{
                
                configOut=new PrintWriter(Projecte.fitxerConfig);
                configOut.print(50);
                configOut.print("12345");
                throw new NumberFormatException();
            }
            
        } catch (NumberFormatException | IOException ex) {
            JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
            p1=new Treballador[8];
        }finally{
            
            try{
                if(configIn!=null)configIn.close();
                if(configOut!=null)configOut.close();
                
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
            }
        }
        
    }

    private void refresca() {
         tc=taula.loadTableFromArray(p1,Treballador.class,false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        telefonText = new javax.swing.JTextField();
        horesText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomText = new javax.swing.JTextField();
        categoriaText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cognomText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taula = new beans.JTableMVCGUI();
        botoInsertar = new javax.swing.JButton();
        botoModificar = new javax.swing.JButton();
        botoBorrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        cridaMenu = new javax.swing.JMenu();
        editaMenu = new javax.swing.JMenu();
        ajudaMenu = new javax.swing.JMenu();
        sobreMenu = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar Treballadors");
        setBackground(new java.awt.Color(102, 0, 0));
        setForeground(new java.awt.Color(102, 0, 0));
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Treballadors de l'Empresa:");

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Ink Free", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CridamTU 1.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel1.setText("Nom:");

        jLabel3.setText("Telefon:");

        jLabel5.setText("Hores:");

        jLabel2.setText("Cognom:");

        jLabel4.setText("Categoria:");

        taula.setBackground(new java.awt.Color(255, 204, 204));
        taula.setForeground(new java.awt.Color(102, 0, 0));
        taula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom", "Cognom", "Telefon", "Categoria", "Hores"
            }
        ));
        taula.setGridColor(new java.awt.Color(255, 204, 204));
        taula.setSelectionBackground(new java.awt.Color(102, 0, 0));
        taula.setSelectionForeground(new java.awt.Color(255, 153, 153));
        taula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taulaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taula);

        botoInsertar.setText("Insertar");
        botoInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoInsertarActionPerformed(evt);
            }
        });

        botoModificar.setText("Modificar");
        botoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoModificarActionPerformed(evt);
            }
        });

        botoBorrar.setText("Borrar");
        botoBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(botoInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(botoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botoBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(93, 93, 93)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(telefonText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(horesText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cognomText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(72, 72, 72)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(categoriaText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(categoriaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cognomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(horesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoInsertar)
                    .addComponent(botoModificar)
                    .addComponent(botoBorrar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 0)));

        cridaMenu.setText("Crida");
        cridaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cridaMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(cridaMenu);

        editaMenu.setText("Editar");
        jMenuBar1.add(editaMenu);

        ajudaMenu.setText("Ajuda");
        ajudaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajudaMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(ajudaMenu);

        sobreMenu.setText("Sobre");
        sobreMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sobreMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(sobreMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void taulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taulaMouseClicked
        // TODO add your handling code here:
        int filaSel=taula.getSelectedRow();
        
        if(filaSel!=-1){
            
            nomText.setText(taula.getModel().getValueAt(filaSel,0).toString());
            cognomText.setText(taula.getModel().getValueAt(filaSel,1).toString());
            telefonText.setText(taula.getModel().getValueAt(filaSel,2).toString());
            categoriaText.setText(taula.getModel().getValueAt(filaSel,3).toString());
            horesText.setText(taula.getModel().getValueAt(filaSel,4).toString());
            
        }else System.out.println(filaSel);
    }//GEN-LAST:event_taulaMouseClicked

    private void botoInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoInsertarActionPerformed
        // TODO add your handling code here:
        Treballador nou=new Treballador();
        try{
            
            nou.set1_nom(nomText.getText().strip());
            nou.set2_cognom(cognomText.getText().strip());
            nou.set3_telefon(Integer.parseInt(telefonText.getText().strip()));
            nou.set4_categoria(categoriaText.getText().strip());
            nou.set5_hores(Integer.parseInt(horesText.getText().strip()));
        
        int i;
            for (i = 0; i < p1.length && p1[i]!=null; i++);
            if(i<p1.length){
                p1[i]=nou;
                refresca();
                if(++plenes==p1.length)botoInsertar.setEnabled(false);
                if(i>0)botoBorrar.setEnabled(true);
                
            }
        }catch(java.lang.NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Tens dades incorrectes!");
        
        }catch(java.lang.NullPointerException ex){
            JOptionPane.showMessageDialog(this,"No pots tenir un numero negatiu!");
        }
    }//GEN-LAST:event_botoInsertarActionPerformed

    private void botoBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoBorrarActionPerformed
        // TODO add your handling code here:
        int filaSel=taula.getSelectedRow();
        
        if(filaSel!=1){
            taula.getColumnModel().addColumn(tc);
            
            Treballador borrar=(Treballador)taula.getModel().getValueAt(filaSel, taula.getColumnCount()-1);
            taula.getColumnModel().removeColumn(tc);
            
            int i;
            for (i = 0; i < p1.length && (p1[i]==null) || !p1[i].equals(borrar); i++);
                if(i<p1.length)
                {
                 
                    p1[i]=null;
                    refresca();
                    JOptionPane.showMessageDialog(this, "El treballador\n\n"+borrar.get1_nom()+" "+borrar.get2_cognom()+"\n\n"+"Ha sigut borrat correctament\n");
                    
                }else JOptionPane.showMessageDialog(this, "Per borrar has de seleccionar una fila");
            
                p1[filaSel]=null;
                refresca();
                botoInsertar.setEnabled(true);
                
                if(--plenes==0)botoBorrar.setEnabled(false);
                 
            }else JOptionPane.showMessageDialog(this, "Per borrar has de seleccionar una fila");
  
         
    }//GEN-LAST:event_botoBorrarActionPerformed

    private void botoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoModificarActionPerformed
        // TODO add your handling code here:
        int filaSel=taula.getSelectedRow();
        
        if(filaSel!=-1){
            //Afegim la columna que conte les plantes a la nostre taula
            taula.getColumnModel().addColumn(tc);
            //Recupero la planta a borrar de la columna que acabo d'afegir
            Treballador modificar=(Treballador)taula.getModel().getValueAt(filaSel, taula.getColumnCount()-1);
           
            taula.getColumnModel().removeColumn(tc);
            
            modificar.set1_nom(nomText.getText().strip());
            modificar.set2_cognom(cognomText.getText());
            modificar.set3_telefon(Integer.parseInt(telefonText.getText()));
            modificar.set4_categoria(categoriaText.getText());
            modificar.set5_hores(Integer.parseInt(horesText.getText()));
            
            refresca();
            JOptionPane.showMessageDialog(this, "El treballador\n\n"+modificar.get1_nom()+" "+modificar.get2_cognom()+"\n\n"+"Ha sigut modificat correctament\n");
            
        }else JOptionPane.showMessageDialog(this, "Per modificar has de seleccionar una fila");
                                           
           
    }//GEN-LAST:event_botoModificarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        ObjectOutputStream sortida=null;
        
        try {
            // TODO add your handling code here:
            sortida=new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream(Projecte.fitxerDades)));
        
            for (int i = 0; i < p1.length; i++) {                
                if(p1[i]!=null)sortida.writeObject(p1[i]);
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
        }finally{
            
            try {
                if(sortida!=null)sortida.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void cridaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cridaMenuMouseClicked
        // TODO add your handling code here:
                        ObjectOutputStream sortida=null;
        
        try {
            // TODO add your handling code here:
            sortida=new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream(Projecte.fitxerDades)));
        
            for (int i = 0; i < p1.length; i++) {                
                if(p1[i]!=null)sortida.writeObject(p1[i]);
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
        }finally{
            
            try {
                if(sortida!=null)sortida.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
            }
        }
     
    
        Window1 v = new Window1(); 
        v.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_cridaMenuMouseClicked

    private void sobreMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobreMenuMouseClicked
        // TODO add your handling code here:
        Sobre a= new Sobre();
        a.setVisible(true);
    }//GEN-LAST:event_sobreMenuMouseClicked

    private void ajudaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajudaMenuMouseClicked
        // TODO add your handling code here:
        Ajuda a= new Ajuda();
        a.setVisible(true);
    }//GEN-LAST:event_ajudaMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajudaMenu;
    private javax.swing.JButton botoBorrar;
    private javax.swing.JButton botoInsertar;
    private javax.swing.JButton botoModificar;
    private javax.swing.JTextField categoriaText;
    private javax.swing.JTextField cognomText;
    private javax.swing.JMenu cridaMenu;
    private javax.swing.JMenu editaMenu;
    private javax.swing.JTextField horesText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomText;
    private javax.swing.JMenu sobreMenu;
    private beans.JTableMVCGUI taula;
    private javax.swing.JTextField telefonText;
    // End of variables declaration//GEN-END:variables

//Les meves propietats
    private Treballador[] p1=null;//creo un array de tipus treballador on guardare els treballadors
    private TableColumn tc;
    private int plenes;
    

}

