/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projecte;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import modeldades.Treballador;

/**
 *
 * @author Palanka
 */
public class Window1 extends javax.swing.JFrame {

    /**
     * Creates new form Window1
     */
    public Window1() {
        initComponents();
        initMyComponents();
    }

    private void initMyComponents() {
        llegirFitxerConfig();
        llegirFitxerDades();

    }
    
    private void llegirFitxerDades(){
        
       if (projecte.Projecte.fitxerDades.exists()){
           
           ObjectInputStream entrada=null;
           int i=0;
           try {
               entrada=new ObjectInputStream(new BufferedInputStream(new FileInputStream(projecte.Projecte.fitxerDades)));

               for(i=0; i<p1.length; i++){
                   
                   p1[i]=(Treballador)entrada.readObject();
                  
               }
                 System.out.println(Arrays.toString(p1));
//            Arrays.sort(p1);

               
           } catch (FileNotFoundException ex) {
               JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
           } catch (IOException ex) {
                   //si entrem aqui es que ha anat tot be
                   System.out.println(Arrays.toString(p1));
//                Arrays.sort(p1);

           } catch (ClassNotFoundException ex) {
               JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
           }finally{
               
               if(entrada!=null)
                   try{
                       entrada.close();
                   }catch (IOException ex){
                       JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
                   }
           
           }
           
       }
       
    }

    private void llegirFitxerConfig() {
        
        BufferedReader configIn=null;
        PrintWriter configOut=null;
        
        try{
            if(projecte.Projecte.fitxerConfig.exists()){
               
                configIn=new BufferedReader(new FileReader(projecte.Projecte.fitxerConfig));
                p1=new Treballador[Integer.parseInt(configIn.readLine().strip())];
            
            }else{
                
                configOut=new PrintWriter(projecte.Projecte.fitxerConfig);
                configOut.print(50);
                configOut.print("12345");
                throw new NumberFormatException();
            }
            
        } catch (NumberFormatException | IOException ex) {
            JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
            p1=new Treballador[8];
        }finally{
            
            try{
                if(configIn!=null)configIn.close();
                if(configOut!=null)configOut.close();
                
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
            }
        }
        
    }

    private void refresca() {
         tc=taula.loadTableFromArray(p3,Treballador.class,false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taula = new beans.JTableMVCGUI();
        necessarisText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        horesText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cridaMenu = new javax.swing.JMenu();
        editaMenu = new javax.swing.JMenu();
        ajudaMenu = new javax.swing.JMenu();
        sobreMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crida de Treballadors");
        setBackground(new java.awt.Color(102, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        taula.setBackground(new java.awt.Color(255, 204, 204));
        taula.setForeground(new java.awt.Color(102, 0, 0));
        taula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom", "Cognom", "Categoria", "Telefon", "Hores"
            }
        ));
        taula.setEnabled(false);
        taula.setGridColor(new java.awt.Color(255, 204, 204));
        taula.setSelectionBackground(new java.awt.Color(102, 0, 0));
        taula.setSelectionForeground(new java.awt.Color(255, 153, 153));
        jScrollPane1.setViewportView(taula);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Treballadors necessaris:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Hores de feina:");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(102, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Crida de treballadors:");

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));

        jLabel2.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CridamTU 1.0 Beta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(necessarisText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(horesText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(162, 162, 162)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(necessarisText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(horesText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 0)));

        cridaMenu.setText("Crida");
        jMenuBar1.add(cridaMenu);

        editaMenu.setText("Editar");
        editaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editaMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(editaMenu);

        ajudaMenu.setText("Ajuda");
        ajudaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajudaMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(ajudaMenu);

        sobreMenu.setText("Sobre");
        sobreMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sobreMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(sobreMenu);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!necessarisText.getText().isEmpty()){
            int cantitat=Integer.parseInt(necessarisText.getText());
            int i;
            for (i = 0; i < p1.length && p1[i]!=null ; i++);

            if(cantitat>i)JOptionPane.showMessageDialog(this,"No tens tans treballadors");
            else{

                p2= new Treballador[i];//aqui esta el fallo

                for(int k=0; k<p2.length;k++){


                    p2[k]=p1[k];

                }
                
                Arrays.sort(p2);
                
                p3= new Treballador[cantitat];//aqui esta el fallo

                for(int k=0; k<p3.length;k++){


                    p3[k]=p2[k];

                }
                
                
                refresca();
            }
    
        }else JOptionPane.showMessageDialog(this,"Has de posar un numero de treballadors");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editaMenuMouseClicked
        // TODO add your handling code here:

        Password a=new Password();
        a.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_editaMenuMouseClicked

    private void sobreMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobreMenuMouseClicked
        // TODO add your handling code here:
        Sobre a= new Sobre();
        a.setVisible(true);
        
    }//GEN-LAST:event_sobreMenuMouseClicked

    private void ajudaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajudaMenuMouseClicked
        // TODO add your handling code here:
        Ajuda a= new Ajuda();
        a.setVisible(true);
    }//GEN-LAST:event_ajudaMenuMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int hores;
        
        if(horesText.getText().isEmpty())horesText.setText("0");
        hores=Integer.parseInt(horesText.getText());
        
        for(int i=0; i<p3.length;i++){
            
            for(int j=0; j<p1.length;j++){
                
                if(p3[i].equals(p1[j])){
                    
                    p1[j].set5_hores(hores+p1[j].get5_hores());
                    System.out.println(p1[j].get5_hores());
                    System.out.println(hores);
                
                }
                 
            }
        }
        
        //aqui copiar arxiu
        
                ObjectOutputStream sortida=null;
        
        try {
            // TODO add your handling code here:
            sortida=new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream(Projecte.fitxerDades)));
        
            for (int i = 0; i < p1.length; i++) {                
                if(p1[i]!=null)sortida.writeObject(p1[i]);
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
        }finally{
            
            try {
                if(sortida!=null)sortida.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,"Atencio possible perdua de dades");
            }
        }
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajudaMenu;
    private javax.swing.JMenu cridaMenu;
    private javax.swing.JMenu editaMenu;
    private javax.swing.JTextField horesText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField necessarisText;
    private javax.swing.JMenu sobreMenu;
    private beans.JTableMVCGUI taula;
    // End of variables declaration//GEN-END:variables
//Les meves propietats
    private Treballador[] p1=null;//creo un array de tipus treballador on guardare els treballadors
    private Treballador[] p2=null;//creo un array de tipus treballador on guardare els treballadors
    private Treballador[] p3=null;//creo un array de tipus treballador on guardare els treballadors
    private TableColumn tc;
    


}


